### ISSUE TITLE
Which keys should be used for github actions?

### ISSUE THREAD

**Issue by berkerdemirer** [rphlmr/supa-fly-stack#13]
Hello,

I am a little bit confused by the read.me file. Should I add prod or staging supabase secrets to github actions secret section?

**Comment by rphlmr** [comment]
Hello,

I'm a bit confused too 😂
Actually ... it depends of your strategy (e2e on staging or production env) 🙃

I forked github ci from Remix indie stack (witch use a sqlite locally and a sqlite "containerized" on fly.io).

I should take a moment to rewrite the readme and the ci :/ 

For the moment, I put my staging database credentials on github secrets, it's just for cypress task.

In real situation, I guess I would still put staging secrets to run cypress on staging env before releasing to production.

+ I think of a step to add : checking if production database has been migrated before "deploy to prod" or adding a step to apply migration (i'm always cautious with steps like that).

Github action is new for me, so, I'm sorry if it's not usable out of the box
