### ISSUE TITLE
Can we define Supabase RLS with Prisma? or somehow with this stack?

### ISSUE THREAD

**Issue by itsmetambui** [rphlmr/supa-fly-stack#29]
Thank you for the awesome stack. I'm new to Prisma and Supabase and would like to understand if it's possible to use Supabase RLS with Prisma?

**Comment by rphlmr** [comment]
Hello, I'm happy if it helps you :)

Using RLS with Prisma is not possible (Prisma use service key to bypass any policies).

If you want RLS on server side, it's possible but only with supabase sdk and a magic tricks :D I can share if I found 1 hour in my schedule

**Comment by rphlmr** [comment]
Currently, I'm working on updating this stack with the latest Remix commits on indie stack (React 18, streaming, cypress 10, etc.)

**Comment by msevestre** [comment]
Yes please 👌

**Comment by itsmetambui** [comment]
> Hello, I'm happy if it helps you :)
> 
> Using RLS with Prisma is not possible (Prisma use service key to bypass any policies).
> 
> If you want RLS on server side, it's possible but only with supabase sdk and a magic tricks :D I can share if I found 1 hour in my schedule

Thank you, and please share your magic tricks when you have the time :D

**Comment by rphlmr** [comment]
Hello there,

You can find a way to use RLS server side with Remix :)

https://github.com/rphlmr/supa-fly-stack/pull/33

**Comment by itsmetambui** [comment]
> Hello there,
> 
> You can find a way to use RLS server side with Remix :)
> 
> 👉 #33

Awesome, thank you for the magic, will check it out.
