### ISSUE TITLE
Possible issues with Cypress mocking?

### ISSUE THREAD

**Issue by itsmetambui** [rphlmr/supa-fly-stack#34]
Hi again, not sure if I'm doing anything wrong but when I run the headless cypress test, the mocking doesn't seem to work and it calls my Supabase API. I can see the users and notes being created and cleaned up in my Supabase dashboard during the tests.

And since it called the actual api, test cases were failing and I had to add this check to wait for the api finishes and route changed to make it pass.
<img width="537" alt="Screen Shot 2022-07-23 at 20 41 52" src="https://user-images.githubusercontent.com/39029320/180607594-7705a482-831c-4e30-b863-317480d58d5f.png">
![smoke tests -- should allow you to make a note (failed)](https://user-images.githubusercontent.com/39029320/180607639-2126f754-bc00-44e2-8b82-5dbb7c283529.png)
![smoke tests -- should allow you to register and login (failed)](https://user-images.githubusercontent.com/39029320/180607641-0d196b6b-ec09-4b93-a423-650785e96248.png)

Steps to reproduce:

1. `npx create-remix --template rphlmr/supa-fly-stack`
2. Correct the `.env` file
3. `npm run setup`
4. `npm run test:e2e:run`

**Comment by rphlmr** [comment]
Sorry for these troubles.

You are right, real api is call and I made a PR to remove mock server when running cypress.
(You can still use It but It requires to mock every thing in your app 🥲)
E2E tests must call real infrastructure to mimic real user experience.

For what you fix, yeah, I have some trouble with cypress and timeout (I made 30+ commits to test various workaround 😱).
I can't reproduce with a fresh install :/

Can you tell me what you have in `cypress.config.ts` ?

**Comment by rphlmr** [comment]
Also, what is your operating system ? Maybe I should add what you propose 🧐

**Comment by itsmetambui** [comment]
Hi @rphlmr, thanks for checking this out.

Yeah, I feel weird to use mocks for e2e too. I guess the only issue left is the test cases fail.
And yeah, same feeling for cypress :D. I'm using MacOS, I'm curious why https://github.com/rphlmr/supa-fly-stack/runs/7480850259?check_suite_focus=true didn't fail?
And my `cypress.config.ts` doesn't have any change, I just pull the latest stack with RLS.

Here's all the checks I had to put in for the test to work.
<img width="488" alt="Screen Shot 2022-07-23 at 21 13 54" src="https://user-images.githubusercontent.com/39029320/180609173-fa19f64b-7f05-49c2-b399-b02f9998b82b.png">

**Comment by rphlmr** [comment]
@itsmetambui really curious, I'm on macOS too 😅

The reason why github action stop fails is that I had `defaultCommandTimeout: process.env.CI ? 30_000 : 4_000` in https://github.com/rphlmr/supa-fly-stack/pull/32

Unless you have a `CI` var env somewhere (`echo $CI` should return nothing), I don't know what is happening.

Remix Grunge stack  (dynamo db) doesn't mock anything in its E2E test (https://github.com/remix-run/grunge-stack/blob/main/cypress/e2e/smoke.cy.ts) or I miss something.

**Comment by rphlmr** [comment]
Maybe you can try to increase `4_000` and tell me if it works ?
If you validate that, I push a PR to increase It

**Comment by itsmetambui** [comment]
@rphlmr you're right, increase `defaultCommandTimeout` locally works, I increased it to `30_000`

**Comment by rphlmr** [comment]
Nice ! I have merge to 30s. Thx
