### ISSUE TITLE
Debugging / Sourcemaps?

### ISSUE THREAD

**Issue by Froskk** [rphlmr/supa-fly-stack#38]
When debugging in vs code, breakpoints are shown in ./build/index.js and not in the original files. Is this expected / Is there a way to get full source map support?

**Comment by rphlmr** [comment]
Hello,

You can follow [this link](https://remix.run/docs/en/v1/other-api/dev#remix-build---sourcemap) 😉

**Comment by Froskk** [comment]
I found the problem was caused by the `mocks/index.js`
```ts
require("tsconfig-paths/register");
require("ts-node").register({ transpileOnly: true });
require("./start");
```

Converting all mocks to plain js restored breakpoints in dev mode

**Comment by rphlmr** [comment]
> I found the problem was caused by the `mocks/index.js`
> 
> ```ts
> 
> require("tsconfig-paths/register");
> 
> require("ts-node").register({ transpileOnly: true });
> 
> require("./start");
> 
> ```
> 
> 
> 
> Converting all mocks to plain js restored breakpoints in dev mode

Oh, I'll try to see what I can do. Thx for your investigation.

**Comment by rphlmr** [comment]
Thank you, @Froskk :)

**Comment by Froskk** [comment]
There may be a more elegant solution that still allows ts in mocks, I think it's the `ts-node` register that is confusing the debugger. May look into it further if I find some time.
