### ISSUE TITLE
Support supabase-js v2 & future of this stack

### ISSUE THREAD

**Issue by rphlmr** [rphlmr/supa-fly-stack#49]
I'll start working on migrating this stack to [supabase-js v2](https://supabase.com/blog/supabase-js-v2).
It's still a release candidate so it'll not be merged to master until it's stable 😉
I think it's possible to create a remix project from a stack's branch name, so, you'll be able to test this in advance.

Maybe some changes will happen on main to prepare for this upgrade.

I plan to :
* make a better readme
* clean some messy things like rewriting RLS and real-time examples, extracting components, etc...
* add some doc on how to delete what you don't want to start your new project

No release date, doing my best 😅

**Comment by rphlmr** [comment]
track https://github.com/rphlmr/supa-fly-stack/pull/52

**Comment by rphlmr** [comment]
I’m working on It and I’ll focus on using Prisma to query database.

I’ll add a note about using Supabase SDK server side (for those using RLS features) : it adds an extra delay due to calling a gotrue rest API instead of directly calling the Postgres database (and this is fine because at first Supabase SDK is for those who doesn't have/want backend).
In my benchmark it’s twice slower.

**Comment by rphlmr** [comment]
V2 is here :) https://github.com/rphlmr/supa-fly-stack/releases/tag/v2.0.0

**Comment by smartsense-as** [comment]
Did you remove all the RLS examples you had in the project?

Any good alternatives for handling authorization in this stack?

**Comment by rphlmr** [comment]
> Did you remove all the RLS examples you had in the project?
> 
> 
> 
> Any good alternatives for handling authorization in this stack?

Yes, I remove It in 2.0
I plan to add it again later but Supabase has released its Remix auth package 😉

https://github.com/supabase/auth-helpers

**Comment by smartsense-as** [comment]
> > Did you remove all the RLS examples you had in the project?
> > Any good alternatives for handling authorization in this stack?
> 
> Yes, I remove It in 2.0 I plan to add it again later but Supabase has released its Remix auth package 😉
> 
> https://github.com/supabase/auth-helpers

Fantastic, I didn't know about this. 

Are you planning on adding it to your stack?

Also I see from the examples in the supabase repo that the method for authorization routes is not very DRY. I'm pretty new to Remix, so can you suggest a cleaner way to implement this logic?

**Comment by rphlmr** [comment]
It's the Remix way to protect every loader with the same code because they are called in parallel.
Until Remix adds a “before loader” hook, we have to do it this 😇

I don't plan to use Remix auth helper because I prefer to show an other way.
I didn't check the code in detail but we do things differently.
In my stack, everything is in
front of you and you are free to learn/modify how it should work for your needs.
