### ISSUE TITLE
Access token refresh not working

### ISSUE THREAD

**Issue by saschatimme** [rphlmr/supa-fly-stack#58]
The `refreshAccessToken` function calls into `supabase-js` using 

https://github.com/rphlmr/supa-fly-stack/blob/bd100e0754adae1922fab4ea6a3f412ea7bf1268/app/modules/auth/service.server.ts#L60-L63

(note `access_token:  ""`)
However, inside supabase we hit the code path 
```
/**
   * Sets the session data from the current session. If the current session is expired, setSession will take care of refreshing it to obtain a new session.
   * If the refresh token or access token in the current session is invalid, an error will be thrown.
   * @param currentSession The current session that minimally contains an access token and refresh token.
   */
  async setSession(currentSession: {
    access_token: string
    refresh_token: string
  }): Promise<AuthResponse> {
    try {
      if (!currentSession.access_token || !currentSession.refresh_token) {
        throw new AuthSessionMissingError()
      }

```
So the code always errors (file can be found at `node_modules/.pnpm/@supabase+gotrue-js@2.6.1/node_modules/@supabase/gotrue-js/src/GoTrueClient.ts` lines 626 and following)

**Comment by saschatimme** [comment]
Just dig a little bit more around and found that there is also the `getSupabaseAdmin().auth.refreshSession` function that only requires a refresh token? Was maybe the intention to call only this?

**Comment by rphlmr** [comment]
Hello, thanks for your report.
In production, I'm on a later version of supabase with no error.

This code was a hack when 2.0 was released and It seems they get back us a refreshSession.

Will try to fix that after Christmas 🎄

**Comment by saschatimme** [comment]
Thanks for the quick response!

You mean an earlier version right? This is appearing in the latest versions of supabase-js (`2.2.1`) and `@supabase/gotrue-js` (`2.6.1`). 

Appreciate that you will take a look :) Happy holidays 🎄

**Comment by rphlmr** [comment]
Thank you all, it should be fixed now.
Will try that on production next week, but seems fine on paper.

I wish you a happy new year :)
