### ISSUE TITLE
Prisma 3.12.0 breaks seed.ts

### ISSUE THREAD

**Issue by sms-swe** [rphlmr/supa-fly-stack#7]
Just a heads up I updated prisma and @prisma/client to 3.12.0 and began getting a 

```
An error occured while running the seed command:
Error: Command was killed with SIGKILL (Forced termination): ts-node --require tsconfig-paths/register prisma/seed.ts
```

I downgraded back to 3.11.1 and everything worked as expected.

**Comment by rphlmr** [comment]
Hello,
Delete your node_modules after prisma update.
It's a know issue from their side since some internals changes ;)

**Comment by SamStephensTPC** [comment]
Ah okay! Sorry about that! Thanks for the info.

**Comment by rphlmr** [comment]
Your are welcome, I searched hours yesterday 😅
