### ISSUE TITLE
Error installing dependences on Ubuntu 22.04

### ISSUE THREAD

**Issue by MaxBroome** [rphlmr/supa-fly-stack#78]
Here's the output from `npm install`

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: shelf@undefined
npm ERR! Found: @remix-run/react@2.3.0
npm ERR! node_modules/@remix-run/react
npm ERR!   @remix-run/react@"^2.3.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @remix-run/react@"^1.0.0" from remix-i18next@4.2.0
npm ERR! node_modules/remix-i18next
npm ERR!   remix-i18next@"^4.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
`

**Comment by rphlmr** [comment]
What is `shelf` package 🧐?
